version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "eu-north-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "MailtrapSsmParameterName=\"/crypto-api/dev/mailtrap/token\" CoinGeckoApiKeySsmParameterName=\"/crypto-api/dev/coingheko/api\""
image_repositories = []
